[build-system]
requires = ["hatchling", "makepatch>=0.2.5"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "work/sources/fastapi/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/alpha93"]


[project]
name = "fastapi-minimal"
dynamic = ["version"]
authors = [{ name = "Alpha", email = "dev@alpha93.kr" }]
requires-python = "==3.14.*"
dependencies = [
    "alpha93",
    "pydantic>=2.9.0",
    "starlette-minimal>=1.0.0",
    "typing-inspection>=0.4.2",
]

[dependency-groups]
dev = [
    "makepatch>=0.2.5",
]

[tool.uv]
exclude-dependencies = [
    "annotated-doc",
    "starlette",
]

[tool.uv.sources]
alpha93 = { path = "../alpha93/packages/commons" }
makepatch = { path = "../makepatch" }
starlette-minimal = { path = "../starlette" }


[tool.hatch.build.hooks.makepatch]
[tool.hatch.build.hooks.makepatch.options]
module-source = "fastapi"
excludes = [
    ".agents/**/*",
    "_compat/**/*",
    "openapi/**/*",
    "middleware/cors.py",
    "middleware/gzip.py",
    "middleware/httpsredirect.py",
    "middleware/trustedhost.py",
    "middleware/wsgi.py",
    "security/oauth2.py",
    "security/open_id_connect_url.py",
    "dependencies/utils.py",
    "__main__.py",
    "cli.py",
    "param_functions.py",
    "staticfiles.py",
    "templating.py",
    "testclient.py",
    "background.py",
    "logger.py",
    "sse.py",
    "types.py",
    "websockets.py",
]
dev-excludes = [
    ".github/**/*",
    "docs/**/*",
    "docs_src/**/*",
    "fastapi-slim/**/*",
    "scripts/**/*",
    "tests/**/*",
    ".pre-commit-config.yaml",
    ".python-version",
    "CITATION.cff",
    "CONTRIBUTING.md",
    "SECURITY.md",
]
