[build-system]
requires = ["hatchling", "makepatch"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "work/sources/fastapi/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/alpha93"]


[project]
name = "fastapi-minimal"
dynamic = ["version"]
authors = [{ name = "Alpha", email = "dev@alpha93.kr" }]
requires-python = "==3.14.*"
dependencies = [
    "alpha93>=0.4.1",
    "pydantic>=2.9.0",
    "starlette-minimal>=1.0.0",
    "typing-inspection>=0.4.2",
]

[dependency-groups]
dev = [
    "alpha93-stubs>=1.0.0",
    "makepatch>=0.2.6",
]

[tool.uv]
exclude-dependencies = [
    "annotated-doc",
    "starlette",
]

[tool.uv.sources]
starlette-minimal = { path = "../starlette" }


[tool.hatch.build.hooks.makepatch.options]
module-source = "fastapi"
excludes = [
    ".agents/**/*",
    "_compat/**/*",
    "openapi/**/*",
    "__main__.py",
    "cli.py",
    "staticfiles.py",
    "templating.py",
    "testclient.py",
    "types.py",
]
dev-excludes = [
    ".github/**/*",
    "docs/**/*",
    "docs_src/**/*",
    "fastapi-slim/**/*",
    "scripts/**/*",
    "tests/**/*",
    ".pre-commit-config.yaml",
    ".python-version",
    "CITATION.cff",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "pyproject.toml",
    "uv.lock",
]
