from collections.abc import Awaitable, Callable, Generator
from contextlib import AbstractAsyncContextManager, contextmanager
from typing import Any, Protocol, TypeIs, TypeVar

from alpha93.commons.types import AwaitableOr

from starlette.types import Scope

def is_async_callable[**P, T](obj: Callable[P, AwaitableOr[T]], /) -> TypeIs[Callable[P, Awaitable[T]]]: ...

_T_co = TypeVar("_T_co", covariant=True)
class AwaitableOrContextManager(Awaitable[_T_co], AbstractAsyncContextManager[_T_co], Protocol[_T_co]): ...

class SupportsAsyncClose(Protocol):
    async def close(self, /): ...

class AwaitableOrContextManagerWrapper[T: SupportsAsyncClose]:
    __slots__ = ("aw", "entered")

    def __init__(self, aw: Awaitable[T], /): ...
    def __await__(self, /) -> Generator[Any, None, T]: ...

    async def __aenter__(self, /) -> T: ...
    async def __aexit__(self, *args) -> bool | None: ...

@contextmanager
def collapse_excgroups() -> Generator: ...

def get_route_path(scope: Scope, /) -> str: ...
