from collections.abc import Callable, Awaitable, Generator
from contextlib import AbstractAsyncContextManager, contextmanager
from typing import Any, TypeIs, overload, TypeVar, Protocol

from starlette.types import Scope


@overload
def is_async_callable[T](obj: Callable[..., Awaitable[T]], /) -> TypeIs[Callable[..., Awaitable[T]]]: ...
@overload
def is_async_callable(obj: Any, /) -> TypeIs[Callable[..., Awaitable[Any]]]: ...

T_co = TypeVar("T_co", covariant=True)
class AwaitableOrContextManager(Awaitable[T_co], AbstractAsyncContextManager[T_co], Protocol[T_co]): ...

class SupportsAsyncClose(Protocol):
    async def close(self, /): ...

class AwaitableOrContextManagerWrapper[T: SupportsAsyncClose]:
    __slots__ = ("aw", "entered")

    def __init__(self, aw: Awaitable[T], /): ...
    def __await__(self, /) -> Generator[Any, None, T]: ...

    async def __aenter__(self, /) -> T: ...
    async def __aexit__(self, *args: Any) -> bool | None: ...

@contextmanager
def collapse_excgroups() -> Generator[None, None, None]: ...

def get_route_path(scope: Scope, /) -> str: ...
