[project]
name = "langchain-core-minimal"
dynamic = ["version"]
authors = [{ name = "Alpha", email = "dev@alpha93.kr" }]
requires-python = "==3.14.*"
dependencies = [
    "alpha93",
]

[dependency-groups]
dev = [
    "makepatch",
]


[tool.uv.sources]
alpha93 = { path = "../alpha93" }
makepatch = { path = "../makepatch" }

[build-system]
requires = ["hatchling", "makepatch"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "work/sources/fastapi/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/alpha93"]

[tool.hatch.build.targets.wheel.force-include]
"src/fastapi" = "fastapi"

[tool.hatch.build.hooks.makepatch]
dependencies = ["makepatch"]

[tool.hatch.build.hooks.makepatch.options]
module-source = "libs/core/langchain_core"
excludes = [
]
dev-excludes = [
    ".devcontainer",
    ".github",
    ".vscode",
    "libs/core/scripts",
    "libs/core/tests",
    "libs/core/Makefile",
    "libs/core/README.md",
    "libs/core/extended_testing_deps.txt",
    "libs/core/pyproject.toml",
    "libs/core/uv.lock",
    "libs/langchain",
    "libs/langchain_v1",
    "libs/model-profiles",
    "libs/partners",
    "libs/standard-tests",
    "libs/text-splitters",
    "libs/Makefile",
    "libs/README.md",
    ".dockerignore",
    ".markdownlint.json",
    ".mcp.json",
    ".pre-commit-config.yaml",
    "AGENTS.md",
    "CITATION.cff",
    "LICENSE",
    "README.md",
]
