"""
This type stub file was generated by pyright.
"""

from typing import NoReturn
from starlette.types import ASGIApp, Message, Receive, Scope, Send

DEFAULT_EXCLUDED_CONTENT_TYPES = ...
class GZipMiddleware:
    def __init__(self, app: ASGIApp, minimum_size: int = ..., compresslevel: int = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    


class IdentityResponder:
    content_encoding: str
    def __init__(self, app: ASGIApp, minimum_size: int) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    
    async def send_with_compression(self, message: Message) -> None:
        ...
    
    def apply_compression(self, body: bytes, *, more_body: bool) -> bytes:
        """Apply compression on the response body.

        If more_body is False, any compression file should be closed. If it
        isn't, it won't be closed automatically until all background tasks
        complete.
        """
        ...
    


class GZipResponder(IdentityResponder):
    content_encoding = ...
    def __init__(self, app: ASGIApp, minimum_size: int, compresslevel: int = ...) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        ...
    
    def apply_compression(self, body: bytes, *, more_body: bool) -> bytes:
        ...
    


async def unattached_send(message: Message) -> NoReturn:
    ...

