[project]
name = "starlette-minimal"
dynamic = ["version"]
authors = [{ name = "Alpha", email = "dev@alpha93.kr" }]
requires-python = "==3.14.*"
dependencies = [
    "alpha93",
    "anyio>=4.13.0",
]

[dependency-groups]
dev = [
    "starlette",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "work/sources/starlette/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/alpha93"]

[tool.hatch.build.targets.wheel.force-include]
"src/starlette" = "starlette"

[tool.hatch.build.hooks.custom]
path = "scripts/hooks/hatch_build.py"

[tool.uv.sources]
starlette = { path = "work/patched" }
alpha93 = { path = "../alpha93" }

[tool.patcher]
module-source = "starlette"
excludes = [
    "websockets.py",
    "types.py",
    "testclient.py",
    "templating.py",
    "staticfiles.py",
    "status.py",
    "schemas.py",
    "formparsers.py",
    "config.py",
    "middleware/sessions.py",
    "middleware/wsgi.py",
]
dev-excludes = [
    ".github/**/*",
    "docs/**/*",
    "scripts/**/*",
    "tests/**/*",
    "mkdocs.yml",
    "CITATION.cff",
]
