[build-system]
requires = ["hatchling", "makepatch>=0.2.5"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "work/sources/starlette/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/alpha93"]


[project]
name = "starlette-minimal"
dynamic = ["version"]
authors = [{ name = "Alpha", email = "dev@alpha93.kr" }]
requires-python = "==3.14.*"
dependencies = [
    "alpha93>=0.4.1",
    "anyio>=4.13.0",
]

[dependency-groups]
dev = [
    "makepatch>=0.2.5"
]

[tool.uv.sources]
makepatch = { path = "../makepatch" }


[tool.ruff]
src = ["src", "work/patched"]

[tool.hatch.build.hooks.makepatch]
[tool.hatch.build.hooks.makepatch.options]
module-source = "starlette"
excludes = [
    "middleware/sessions.py",
    "middleware/wsgi.py",
    "config.py",
    "formparsers.py",
    "routing.py",
    "schemas.py",
    "staticfiles.py",
    "status.py",
    "templating.py",
    "testclient.py",
    "types.py",
    "websockets.py",
]
dev-excludes = [
    ".github/**/*",
    "docs/**/*",
    "scripts/**/*",
    "tests/**/*",
    "mkdocs.yml",
    "CITATION.cff",
]
