"""
This type stub file was generated by pyright.
"""

import sys
from collections.abc import Awaitable, Callable, Generator
from contextlib import AbstractAsyncContextManager, contextmanager
from typing import Any, Generic, Protocol, TypeIs, TypeVar, overload
from starlette.types import Scope

if sys.version_info >= (3, 13):
    ...
else:
    ...
has_exceptiongroups = ...
if sys.version_info < (3, 11):
    ...
T = TypeVar("T")
AwaitableCallable = Callable[..., Awaitable[T]]
@overload
def is_async_callable(obj: AwaitableCallable[T]) -> TypeIs[AwaitableCallable[T]]:
    ...

@overload
def is_async_callable(obj: Any) -> TypeIs[AwaitableCallable[Any]]:
    ...

def is_async_callable(obj: Any) -> Any:
    ...

T_co = TypeVar("T_co", covariant=True)
class AwaitableOrContextManager(Awaitable[T_co], AbstractAsyncContextManager[T_co], Protocol[T_co]):
    ...


class SupportsAsyncClose(Protocol):
    async def close(self) -> None:
        ...
    


SupportsAsyncCloseType = TypeVar("SupportsAsyncCloseType", bound=SupportsAsyncClose, covariant=False)
class AwaitableOrContextManagerWrapper(Generic[SupportsAsyncCloseType]):
    __slots__ = ...
    def __init__(self, aw: Awaitable[SupportsAsyncCloseType]) -> None:
        ...
    
    def __await__(self) -> Generator[Any, None, SupportsAsyncCloseType]:
        ...
    
    async def __aenter__(self) -> SupportsAsyncCloseType:
        ...
    
    async def __aexit__(self, *args: Any) -> None | bool:
        ...
    


@contextmanager
def collapse_excgroups() -> Generator[None, None, None]:
    ...

def get_route_path(scope: Scope) -> str:
    ...

