"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping

class HTTPException(Exception):
    def __init__(self, status_code: int, detail: str | None = ..., headers: Mapping[str, str] | None = ...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


class WebSocketException(Exception):
    def __init__(self, code: int, reason: str | None = ...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


